"use client"

import { useEffect, useRef } from "react"
import {
  Control,
  FieldArrayPath,
  Path,
  useFieldArray,
  useFormContext,
} from "react-hook-form"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { NumberInput } from "@/components/input/NumberInput"
import { MenuOptionFields } from "./MenuOptionFields"
import { MenuFormValueOptions } from "@/lib/option-utils"

const MAX_DEPTH = 3

type Props = {
  control: Control<MenuFormValueOptions>
  name: Path<MenuFormValueOptions>
  remove: () => void
  level?: number
  parentValue?: string
}

export function ChoiceFields({
  control,
  name,
  remove,
  level = 0,
  parentValue = "",
}: Props) {
  const { register, watch, setValue } =
    useFormContext<MenuFormValueOptions>()

  const labelValue = watch(
    `${name}.label` as Path<MenuFormValueOptions>
  ) as string | undefined

  const currentValue = watch(
    `${name}.value` as Path<MenuFormValueOptions>
  ) as string | undefined

  const isAutoGenerated = useRef(true)

  const {
    fields: subOptionFields,
    append,
    remove: removeSub,
  } = useFieldArray({
    control,
    name: `${name}.subOptions` as FieldArrayPath<MenuFormValueOptions>,
  })

  /**
   * 🔥 Auto generate hierarchical value
   * Format: Parent Label Child Label
   * Example: "Size Large Extra Cheese"
   */
  useEffect(() => {
    if (!labelValue) return

    // kalau user pernah edit manual, stop auto generate
    if (!isAutoGenerated.current) return

    const finalValue = parentValue
      ? `${parentValue} ${labelValue}`
      : labelValue

    setValue(
      `${name}.value` as Path<MenuFormValueOptions>,
      finalValue,
      { shouldValidate: true }
    )
  }, [labelValue, parentValue, name, setValue])

  /**
   * Detect manual edit
   */
  const normalize = (text: string) =>
    text
      .toLowerCase()
      .trim()
      .replace(/\s+/g, "_")
      .replace(/[^a-z0-9_]/g, "")
      
  useEffect(() => {
    if (!labelValue) return
    if (!isAutoGenerated.current) return

    const currentSlug = normalize(labelValue)

    const finalValue = parentValue
      ? `${parentValue} ${currentSlug}`
      : currentSlug

    setValue(
      `${name}.value` as Path<MenuFormValueOptions>,
      normalize(finalValue),
      { shouldValidate: true }
    )
  }, [labelValue, parentValue, name, setValue])

  return (
    <div className="pl-4 ml-3 border-l border-muted space-y-3">
      <div className="flex gap-2 items-center">
        {/* LABEL */}
        <Input
          {...register(`${name}.label` as Path<MenuFormValueOptions>)}
          placeholder="Choice"
          className="max-w-xs"
        />

        {/* EXTRA PRICE */}
        <NumberInput
          control={control}
          name={`${name}.extraPrice` as Path<MenuFormValueOptions>}
          currency
          currencyCode="IDR"
        />

        {/* REMOVE */}
        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={remove}
        >
          ✕
        </Button>
      </div>

      {/* Hidden VALUE */}
      <Input
        type="hidden"
        {...register(`${name}.value` as Path<MenuFormValueOptions>)}
      />

      {/* RECURSIVE SUB OPTIONS */}
      {subOptionFields.map((field, index) => (
        <MenuOptionFields
          key={field.id}
          control={control}
          name={`${name}.subOptions.${index}` as Path<MenuFormValueOptions>}
          remove={() => removeSub(index)}
          level={level + 1}
          parentValue={currentValue || ""}
        />
      ))}

      {level < MAX_DEPTH && (
        <Button
          type="button"
          variant="ghost"
          size="sm"
          className="text-muted-foreground"
          onClick={() =>
            append({
              id: crypto.randomUUID(),
              label: "",
              value: "",
              extraPrice: 0,
              type: "single",
              required: false,
              choices: [],
            })
          }
        >
          + Add Sub Option
        </Button>
      )}
    </div>
  )
}